version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  mongo-express:
    container_name: mongo-express-container
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: thiago
      ME_CONFIG_BASICAUTH_PASSWORD: 12345
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
    links:
      - mongo
    networks:
      - mongo-compose-network
  # api:
  #   container_name: api-container
  #   image: node:14
  #   working_dir: /usr/src/prometheus-express
  #   restart: always
  #   command: bash -c "npm install && npm start"
  #   environment:
  #     - MONGO_URL=mongodb://mongo:27017/prometheus-express
  #   volumes:
  #     - ./dist/:/usr/src/prometheus-express/dist/
  #     - ./package.json:/usr/src/prometheus-express/package.json
  #   ports:
  #     - "5050:5050"
  #     - "9222:9222"
  #   links:
  #     - mongo

networks:
  mongo-compose-network:
    driver: bridge
